/**
 * Assembles renderer/index.html from renderer/partials.
 *
 * The window is one document, but it was also one 1,600-line file, which made
 * it the single thing everybody had to edit and nobody could edit at the same
 * time. Splitting it by surface means a change to the Worker page and a change
 * to the sidebar touch different files and cannot silently overwrite each
 * other.
 *
 * There is no include mechanism to lean on: the renderer is sandboxed under a
 * strict content security policy, so this cannot be done at runtime with fetch
 * or with a template library. It is done at build time instead, which is the
 * same shape as build-tokens and build-icons and costs nothing at startup.
 *
 *     node scripts/build-markup.mjs [--check]
 *
 * `--check` fails instead of writing, for CI.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const renderer = path.join(here, '..', 'renderer')
const partials = path.join(renderer, 'partials')
const output = path.join(renderer, 'index.html')

/**
 * The document, in order, and who owns each piece.
 *
 * The owner column is not decoration. It is the answer to "may I edit this",
 * which is the question that decides whether parallel work is safe.
 */
const DOCUMENT = [
  ['head.html', 'shared — stylesheet links and the content security policy'],
  ['sprite.html', 'generated by build-icons.mjs; do not edit'],
  ['titlebar.html', 'window chrome'],
  ['onboarding.html', 'first run'],
  ['settings.html', 'settings overlay'],
  ['shell-open.html', 'shared — opens main.shell'],
  ['sidebar.html', 'sidebar and its footer'],
  ['content-open.html', 'shared — opens section.content'],
  ['panel-chat.html', 'chat, the room and its header'],
  ['panel-models.html', 'models and inference'],
  ['panel-worker.html', 'worker'],
  ['panel-wallet.html', 'wallet'],
  ['content-close.html', 'shared — closes content and shell'],
  ['dialogs.html', 'shared dialogs: join, invite, pay, rename, move'],
  ['dialog-secure.html', 'how this room is protected'],
  ['foot.html', 'shared — toast, module script, closing tags']
]

const HEADER = `<!--
  Generated by scripts/build-markup.mjs from renderer/partials. Do not edit.

  Editing this file directly works until the next build, which is the worst
  kind of works. Change the partial instead:

${DOCUMENT.map(([file, owner]) => `    partials/${file.padEnd(22)} ${owner}`).join('\n')}
-->
`

const missing = DOCUMENT.map(([file]) => file).filter(
  (file) => !fs.existsSync(path.join(partials, file))
)
if (missing.length > 0) {
  console.error(`missing partial(s): ${missing.join(', ')}`)
  process.exit(1)
}

const pieces = DOCUMENT.map(([file]) => fs.readFileSync(path.join(partials, file), 'utf8'))

// Every partial is stored with a trailing newline so the files are ordinary
// text; joining on nothing keeps the assembled document from growing a blank
// line at each seam on every build.
const next = HEADER + pieces.map((piece) => piece.replace(/\n$/, '')).join('\n') + '\n'
const current = fs.existsSync(output) ? fs.readFileSync(output, 'utf8') : null

if (process.argv.includes('--check')) {
  if (next !== current) {
    console.error('renderer/index.html is out of date; run node scripts/build-markup.mjs')
    process.exit(1)
  }
  console.log(`index.html is current (${DOCUMENT.length} partials)`)
} else {
  fs.writeFileSync(output, next)
  console.log(`assembled renderer/index.html from ${DOCUMENT.length} partials`)
}
