import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { cssVariables, conventions } from '@lcai-p2p/ui'

/**
 * Generates the renderer's token stylesheet from @lcai-p2p/ui.
 *
 * The renderer runs sandboxed and cannot import modules, so the tokens have to
 * arrive as plain CSS. Generating that file rather than hand-maintaining it is
 * what stops the interface and the design system drifting apart — a copied hex
 * value is a copy that will be wrong eventually.
 *
 * Platform font stacks are all emitted; the renderer picks one from a data
 * attribute the main process sets, since it cannot detect the platform itself.
 */

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'renderer', 'tokens.css')

const css = `/* Generated by scripts/build-tokens.mjs from @lcai-p2p/ui. Do not edit. */

:root,
:root[data-theme='dark'] {
  ${cssVariables('dark')}
}

:root[data-theme='light'] {
  ${cssVariables('light')}
}

:root[data-platform='win32'] {
  --lc-font: ${conventions('win32').fontStack};
}

:root[data-platform='darwin'] {
  --lc-font: ${conventions('darwin').fontStack};
}

:root[data-platform='linux'] {
  --lc-font: ${conventions('linux').fontStack};
}
`

writeFileSync(out, css)
console.log(`wrote ${out}`)
