import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { cssVariables, conventions, MOTION } from '@lcai-p2p/ui'

/**
 * Generates the renderer's token stylesheet from @lcai-p2p/ui.
 *
 * The renderer runs sandboxed and cannot import modules, so the tokens have to
 * arrive as plain CSS. Generating that file rather than hand-maintaining it is
 * what stops the interface and the design system drifting apart — a copied hex
 * value is a copy that will be wrong eventually.
 *
 *     node scripts/build-tokens.mjs           write it
 *     node scripts/build-tokens.mjs --check   fail if it is not what would be written
 *
 * The check mode exists because this was the one generator without one. A hand
 * edit here produces no error and no symptom: the value resolves, the interface
 * uses it, every other check passes, and the change vanishes the next time
 * anybody builds. That is a worse failure than a broken build.
 *
 * Platform font stacks are all emitted; the renderer picks one from a data
 * attribute the main process sets, since it cannot detect the platform itself.
 */

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'renderer', 'tokens.css')

const css = `/* Generated by scripts/build-tokens.mjs from @lcai-p2p/ui. Do not edit. */

/*
 * Inter, the website's face, bundled rather than fetched: the window's policy
 * allows no remote origin. The files and these two rules are Lightchain
 * Studio's (fork-tools/overlay/.../media/fonts, apply-source-patches.py:64-70),
 * Google Fonts' v20 latin and latin-ext subsets, as lightchain.ai loads them.
 */
@font-face {
  font-family: 'Inter';
  src: url('./fonts/Inter-latin.woff2') format('woff2');
  font-weight: 100 900;
  font-display: block;
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

@font-face {
  font-family: 'Inter';
  src: url('./fonts/Inter-latin-ext.woff2') format('woff2');
  font-weight: 100 900;
  font-display: block;
  unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
}

:root {
  ${cssVariables()}
}

/*
 * Motion, switched off at the source.
 *
 * Redefining the three duration tokens is what makes this one decision rather
 * than a media query beside every transition. A rule written as
 * \`transition: opacity var(--lc-motion-base) var(--lc-easing)\` honours the
 * preference without knowing it exists, which is the only version that stays
 * true as rules are added.
 */
@media (prefers-reduced-motion: reduce) {
  :root {
    --lc-motion-fast: 0ms;
    --lc-motion-base: 0ms;
    --lc-motion-slow: 0ms;
  }
}

/* Kept for anything that has to reach a real duration regardless. */
:root {
  --lc-motion-fast-fixed: ${MOTION.fast}ms;
  --lc-motion-base-fixed: ${MOTION.base}ms;
  --lc-motion-slow-fixed: ${MOTION.slow}ms;
}

:root[data-platform='win32'] {
  --lc-font: ${conventions('win32').fontStack};
}

:root[data-platform='darwin'] {
  --lc-font: ${conventions('darwin').fontStack};
}

:root[data-platform='linux'] {
  --lc-font: ${conventions('linux').fontStack};
}
`

if (process.argv.includes('--check')) {
  let onDisk = null
  try {
    onDisk = readFileSync(out, 'utf8')
  } catch {
    console.error('tokens.css is missing. Run `node scripts/build-tokens.mjs`.')
    process.exit(1)
  }

  if (onDisk !== css) {
    console.error('tokens.css is not what @lcai-p2p/ui would generate.')
    console.error('Either a token changed and it was not rebuilt, or the file was edited by hand.')
    console.error('Run `node scripts/build-tokens.mjs`.')
    process.exit(1)
  }

  const count = (css.match(/--lc-[a-z0-9-]+:/g) ?? []).length
  console.log(`tokens.css is current (${count} declarations)`)
} else {
  writeFileSync(out, css)
  console.log(`wrote ${out}`)
}
